# --------------------------------------------------------------------------
#
# Copyright (c) Microsoft Corporation. All rights reserved.
#
# The MIT License (MIT)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the ""Software""), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED *AS IS*, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.
#
# --------------------------------------------------------------------------
"""Shared utilities for polling continuation-token serialization.

The token format is base64-encoded ``pickle`` (matching the pre-CVE-2026-21226
shape) for full backward compatibility with tokens issued by older azure-core
versions. The CVE is mitigated by routing the decode path through
:class:`_SafeUnpickler`, which constrains :py:meth:`pickle.Unpickler.find_class`
to an allowlist of data-shaped types reachable from a real continuation-token
payload.

This is a defense-in-depth hardening, not a guarantee — ``pickle``'s
``BUILD``/``REDUCE`` opcodes can still trigger side effects on allowed classes.
Do not decode continuation tokens from sources you do not trust.
"""

import base64
import io
import pickle
from typing import Any


_TOKEN_DECODE_ERROR_MESSAGE = (
    "Unable to decode continuation token. It may be corrupted or generated by "
    "an incompatible version of azure-core."
)


# Allowlist consulted by :class:`_SafeUnpickler.find_class`. Each entry is a
# (module, qualified-name) pair that pickle is permitted to resolve. Only data
# primitives constructed via dedicated pickle opcodes (list/tuple/dict/str/int…)
# bypass find_class — they do not need to be listed here.
#
# This list is intentionally minimal: every class is a fresh slice of attack
# surface (its ``__setstate__`` / ``__init__`` / descriptors run with
# attacker-controlled state during unpickling). Add a new entry only when a
# legitimate continuation token from a supported azure-core path fails to
# decode with ``ValueError: Refusing to load … not in the
# continuation-token allowlist``.
_PICKLE_ALLOWED_CLASSES = frozenset(
    [
        # azure-core pipeline / transport / rest types reachable from a pickled
        # PipelineResponse.
        ("azure.core.pipeline", "PipelineResponse"),
        ("azure.core.pipeline", "PipelineContext"),
        ("azure.core.pipeline.transport._base", "HttpRequest"),  # legacy HttpRequest path
        ("azure.core.pipeline.transport._requests_basic", "RequestsTransportResponse"),
        ("azure.core.pipeline.transport._requests_basic", "StreamDownloadGenerator"),
        ("azure.core.pipeline.transport._requests_asyncio", "AsyncioRequestsTransportResponse"),
        ("azure.core.pipeline.transport._requests_asyncio", "AsyncioStreamDownloadGenerator"),
        ("azure.core.pipeline.transport._requests_trio", "TrioRequestsTransportResponse"),
        ("azure.core.pipeline.transport._aiohttp", "AioHttpTransportResponse"),
        ("azure.core.pipeline.transport._aiohttp", "AioHttpStreamDownloadGenerator"),
        ("azure.core.rest._rest_py3", "HttpRequest"),  # new HttpRequest path
        ("azure.core.rest._requests_basic", "RestRequestsTransportResponse"),
        ("azure.core.rest._requests_basic", "_CaseInsensitiveDict"),
        ("azure.core.rest._requests_asyncio", "RestAsyncioRequestsTransportResponse"),
        ("azure.core.rest._requests_trio", "RestTrioRequestsTransportResponse"),
        ("azure.core.rest._aiohttp", "RestAioHttpTransportResponse"),
        ("azure.core.rest._aiohttp", "_CIMultiDict"),
        ("azure.core.utils._utils", "CaseInsensitiveDict"),
        # requests-library types nested inside RequestsTransportResponse.
        ("requests.models", "Response"),
        ("requests.models", "PreparedRequest"),
        ("requests.cookies", "RequestsCookieJar"),
        ("requests.structures", "CaseInsensitiveDict"),
        # multidict (aiohttp's underlying header storage)
        ("multidict._multidict", "CIMultiDict"),
        ("multidict._multidict", "istr"),
        ("multidict", "CIMultiDict"),
        ("multidict", "istr"),
        # stdlib helpers used by pickle to reconstruct allowlisted classes.
        # copyreg._reconstructor is safe to allow because the class it
        # reconstructs is itself resolved via find_class — the per-class
        # allowlist still applies.
        ("copyreg", "_reconstructor"),
        ("http.cookiejar", "DefaultCookiePolicy"),
        ("collections", "OrderedDict"),
        ("datetime", "timedelta"),
        ("builtins", "dict"),  # PipelineContext.__reduce_ex__ names dict as the base class
    ]
)


class _SafeUnpickler(pickle.Unpickler):  # noqa: cspell:disable-line
    """Restricted :class:`pickle.Unpickler` whose ``find_class`` rejects any
    class not in :data:`_PICKLE_ALLOWED_CLASSES`.

    Used as the sole decode path for continuation tokens to mitigate
    CVE-2026-21226 (``pickle.loads`` RCE) while preserving the legacy
    token wire format.
    """

    def find_class(self, module: str, name: str):
        if (module, name) in _PICKLE_ALLOWED_CLASSES:
            return super().find_class(module, name)
        raise pickle.UnpicklingError(
            "Refusing to load {0}.{1!r}: not in the continuation-token allowlist.".format(module, name)
        )


def _encode_continuation_token(data: Any) -> str:
    """Encode an object as a base64-encoded pickle continuation token.

    :param data: The object to encode. Must be pickle-serializable.
    :type data: any
    :return: The base64-encoded pickle string.
    :rtype: str
    """
    return base64.b64encode(pickle.dumps(data)).decode("ascii")


def _decode_continuation_token(continuation_token: str) -> Any:
    """Decode a base64-encoded pickle continuation token through
    :class:`_SafeUnpickler`.

    :param continuation_token: The base64-encoded continuation token.
    :type continuation_token: str
    :return: The unpickled object.
    :raises ValueError: If the token cannot be decoded under the allowlist
        (corrupt token, or an attempt to load a disallowed class — see
        CVE-2026-21226).
    """
    try:
        decoded_bytes = base64.b64decode(continuation_token)
        return _SafeUnpickler(io.BytesIO(decoded_bytes)).load()
    except (pickle.UnpicklingError, EOFError, AttributeError, ValueError, TypeError, ImportError) as err:
        raise ValueError(_TOKEN_DECODE_ERROR_MESSAGE) from err
